## Dealing with Missing

In [1]:
import pandas as pd
from io import StringIO

data = '''A,B,C,D 
1.0,2.0,3.0,4.0
5.0,6.0,,8.0
10.0,11.0,12.0,'''

df = pd.read_csv(StringIO(data)) 
#Stringio help read the data as file since read_csv expects csv data as file

print(df)
print(df.isnull().sum())

print(df.values)

      A     B     C   D 
0   1.0   2.0   3.0  4.0
1   5.0   6.0   NaN  8.0
2  10.0  11.0  12.0  NaN
A     0
B     0
C     1
D     1
dtype: int64
[[ 1.  2.  3.  4.]
 [ 5.  6. nan  8.]
 [10. 11. 12. nan]]


ELiminating missing values

In [2]:
df.dropna(axis = 0) # ELimanatin rows with nan

print(df.dropna(axis = 0))

df.dropna(axis=1) # eliman column

print(df.dropna(axis = 1))

# To drop the colum with all nan  uses how = all instead of the axis =1

# to drop only specific column use subset = 'Column Name'

# To drop only the rows with fewer than no, use thres = 'No'

     A    B    C   D 
0  1.0  2.0  3.0  4.0
      A     B
0   1.0   2.0
1   5.0   6.0
2  10.0  11.0


Inputting   The missing values using imput

In [3]:
from sklearn.impute import SimpleImputer
import numpy as np

miss = SimpleImputer(missing_values= np.nan,strategy= "mean")
miss.fit(df.values)
Impute_Data = miss.transform(df.values)

print(Impute_Data)

# Also we can use ; it replaces the nan with mean

print(df.fillna(df.mean()))

[[ 1.   2.   3.   4. ]
 [ 5.   6.   7.5  8. ]
 [10.  11.  12.   6. ]]
      A     B     C   D 
0   1.0   2.0   3.0  4.0
1   5.0   6.0   7.5  8.0
2  10.0  11.0  12.0  6.0


# HANDLING CATEGORICAL DATA

In [11]:
dyat = pd.DataFrame([['Green','M',10.1,'Class 2'],
                    ['red','L',13.5,'Class 1'],
                    ['blue','XL',15.3,'Class 2']])
dyat.columns = ['Color','Size', 'Price','ClasssLabel']
dyat

Color Size  Price ClasssLabel
0  Green    M   10.1     Class 2
1    red    L   13.5     Class 1
2   blue   XL   15.3     Class 2

In [12]:
size_mapping = {'M':1, 'L': 2, 'XL':3}

dyat['Size'] = dyat['Size'].map(size_mapping)

dyat

Color  Size  Price ClasssLabel
0  Green     1   10.1     Class 2
1    red     2   13.5     Class 1
2   blue     3   15.3     Class 2

Class Mapping using sklearn

In [ ]:
from sklearn.preprocessing import LabelEncoder

cls_lab = LabelEncoder()

y = cls_lab.fit_transform(dyat['ClasssLabel'])

#TO TRANSFORM BACK
cls_lab.inverse_transform(y)
#print(y)

[1 0 1]


# Performing one-hot encoding on nominal features

In [27]:
from sklearn.preprocessing import OneHotEncoder
dyat
# Converting  The color to the integer
X= dyat[['Color','Size','Price']].values
# X[:,0] = cls_lab.fit_transform(X[:,0])

colr_enc =  OneHotEncoder()

re = colr_enc.fit_transform(X[:,0].reshape(-1,1)).toarray()
print(re)
#Please not it  has convert to 100,010,001 based on binary

# If we wanted to select multiple columne we could have used COlumn transformer

# Another simpler way is using get dummies
pd.get_dummies(dyat[['Color','Size','Price']], drop_first= True)

# and If you can note we can remove one feature such as gree which won`ts affect anything` since other colors are well represented









[[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]


Size  Price  Color_blue  Color_red
0     1   10.1       False      False
1     2   13.5       False       True
2     3   15.3        True      False

## Partitioning a dataset into separate training and test datasets